version: '3'
volumes:
  mysql_data:
 
services:
  nodechat:
    build:
       context: ./
       dockerfile: Dockerfile.mysql
    container_name: nodechat
    volumes:    
     - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: smoot
      MYSQL_USER: "local"
      MYSQL_PASSWORD: "local"
    ports:
     - "8089:3306"  # let outside world see 8089
    networks:
    - bazaar-net
  bazaar:
    build: 
       context: ./
       dockerfile: Dockerfile
    container_name: bazaar
    depends_on:
     - nodechat
    networks:
    - bazaar-net
  front:
    build: ./ha-proxy
    image: bazaar/haproxy
    container_name: bazaar-haproxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - bazaar
    networks:
      - bazaar-net
networks:
  bazaar-net:
    driver: bridge
