version: '3'
volumes:
  mysql_data:
 
services:
  nodechat:
    build:
       context: ./
       dockerfile: Dockerfile.mysql
    container_name: nodechat_http
    volumes:    
     - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ******
      MYSQL_USER: "******"
      MYSQL_PASSWORD: "******"
    networks:
    - bazaar-net
  bazaar:
    build: 
       context: ./
       dockerfile: Dockerfile
    container_name: bazaar_http
    depends_on:
     - nodechat
    ports:
     - "8000:80"
    networks:
    - bazaar-net
networks:
  bazaar-net:
    driver: bridge
